#!/usr/bin/env python
import sys
import glob
import datetime
import os
import shutil
from quik import FileLoader

def modified_at(path):
    return datetime.datetime.fromtimestamp(os.path.getmtime(path))

def build():
    print("building site...")
    data = { 'news': [], 'files': [] }
    
    for path in glob.glob('./public/files/*'):
        f = path.replace('./public/files/', '').split('_')
        data['files'].append({ 'url': path, 'category': f[0] , 'basename': f[1], 'date': modified_at(path) })
        
    data['files'].sort(key = lambda k: k['date'])
    data['news'].sort(key = lambda k: k['date'], reverse = True)

    tpl = FileLoader('./_site').load_template('layout.html')
    out = bytes(tpl.render(data), 'utf-8')
    
    os.remove('./index.html')
    open('./index.html', 'wb').write(out)
    print("Done!")
    
# CLI interface
commands = {
    'build': build
}

commands[sys.argv[1]]()
